import { useState, type ReactNode } from "react";
import { createBrowserRouter, Link, RouterProvider, useParams, useSearchParams } from "react-router";
import { ImageWithFallback } from "./components/figma/ImageWithFallback";
import noise from "../imports/Group31-2/58ba9031907cfe5b00acc9f115b3f6e061416a08.png";
import hero from "../imports/Group31-2/22846d111fb4f3ef7c744379fb496382e445b692.png";
import woman1 from "../imports/Group31-2/1a771283c98217b3f7ba2bc204d0e9e9568c9019.png";
import woman2 from "../imports/Group31-2/44ae9c14e7cacd30490e7a84cc5b75908c1a0cb3.png";
import woman3 from "../imports/Group31-2/0b27a8697ced4dc3ab0c19c9bce0e013fbc1fe83.png";
import woman4 from "../imports/Group31-2/04f35790064fb7a24e9a9e58094d851550dc177c.png";
import woman5 from "../imports/Group31-2/a785342e5d8a34ed7ebda9cd3e44e739fc976777.png";
import man1 from "../imports/Group31-2/3c8f8ce2676bb9af3f503a30874053370bd786a4.png";
import man2 from "../imports/Group31-2/c324c46f1d424035ccc1375b46e54f8f2b0f871e.png";
import man3 from "../imports/Group31-2/52d29a2dba17ad65cc5edcadf5b74ef35cff7403.png";
import man4 from "../imports/Group31-2/671545d05abdb4762a53763afd28e9cbe72672d2.png";
import detailMain from "../imports/Group33-1/22846d111fb4f3ef7c744379fb496382e445b692.png";
import detail1 from "../imports/Group33-1/1a771283c98217b3f7ba2bc204d0e9e9568c9019.png";
import detail2 from "../imports/Group33-1/44ae9c14e7cacd30490e7a84cc5b75908c1a0cb3.png";
import detail3 from "../imports/Group33-1/0b27a8697ced4dc3ab0c19c9bce0e013fbc1fe83.png";

const clients = ["TSUM", "LIME", "STUDIO 21", "12 STOREEZ", "RBC STYLE", "VOGUE", "PRESENT & SIMPLE", "GATE31", "GRAZIA", "LOVE REPUBLIC", "ELLE", "LAMODA"];
const modelStats = [["Рост", "176"], ["Бюст", "84"], ["Талия", "60"], ["Бедра", "90"], ["Обувь", "39"], ["Волосы", "Блонд"]];
const models = [
  { id: "elvira-vaitovich", gender: "women", name: "Эльвира Вайтович", category: "ЖЕНЩИНЫ / NEW FACE", image: hero, shots: [detail1, detail2, detail3], stats: modelStats },
  { id: "alisa-mironova", gender: "women", name: "Алиса Миронова", category: "ЖЕНЩИНЫ", image: woman1, shots: [woman2, woman3, woman4], stats: [["Рост", "178"], ["Бюст", "82"], ["Талия", "59"], ["Бедра", "88"], ["Обувь", "38"], ["Волосы", "Русый"]] },
  { id: "maria-kane", gender: "women", name: "Мария Кейн", category: "ЖЕНЩИНЫ", image: woman2, shots: [woman1, woman3, woman5], stats: modelStats },
  { id: "vera-sol", gender: "women", name: "Вера Соль", category: "ЖЕНЩИНЫ / NEW FACE", image: woman3, shots: [woman4, woman1, woman2], stats: modelStats },
  { id: "nikita-volkov", gender: "men", name: "Никита Волков", category: "МУЖЧИНЫ", image: man1, shots: [man2, man3, man4], stats: [["Рост", "188"], ["Грудь", "94"], ["Талия", "76"], ["Бедра", "92"], ["Обувь", "43"], ["Волосы", "Брюнет"]] },
  { id: "ivan-sokolov", gender: "men", name: "Иван Соколов", category: "МУЖЧИНЫ / NEW FACE", image: man2, shots: [man1, man3, man4], stats: [["Рост", "186"], ["Грудь", "92"], ["Талия", "74"], ["Бедра", "91"], ["Обувь", "42"], ["Волосы", "Шатен"]] },
  { id: "mark-orson", gender: "men", name: "Марк Орсон", category: "МУЖЧИНЫ", image: man3, shots: [man1, man2, man4], stats: [["Рост", "190"], ["Грудь", "96"], ["Талия", "78"], ["Бедра", "94"], ["Обувь", "44"], ["Волосы", "Блонд"]] },
];

function Plus({ light = false }: { light?: boolean }) {
  return <span className={`relative inline-block size-10 ${light ? "text-card" : "text-foreground"}`}><span className="absolute left-[18px] top-0 h-10 w-[3px] bg-current" /><span className="absolute left-0 top-[18px] h-[3px] w-10 bg-current" /></span>;
}

function Header() {
  return <header className="sticky top-0 z-50 h-[102px] border-b border-border bg-[#fbf4f4]/95 backdrop-blur-sm"><div className="mx-auto flex h-full max-w-[1440px] items-center justify-between px-7 text-[#2a2929]"><Link to="/" className="font-serif text-[42px] leading-none tracking-[-.18em]" style={{ fontFamily: "Italiana, serif" }}>RF</Link><Link to="/" className="hidden items-center gap-3 text-2xl font-medium md:flex"><span className="flex flex-col gap-1"><i className="block h-1 w-7 bg-current" /><i className="ml-2 block h-1 w-7 bg-current" /></span>МЕНЮ</Link><nav className="flex flex-wrap justify-end gap-x-6 gap-y-2 text-sm font-semibold uppercase tracking-[.04em] md:text-2xl md:font-medium md:tracking-normal"><Link to="/brief" className="transition hover:text-primary">ПРОЙТИ КАСТИНГ</Link><Link to="/contacts" className="transition hover:text-primary">КОНТАКТЫ</Link><Link to="/?gender=men" className="transition hover:text-primary">МУЖЧИНЫ</Link><Link to="/?gender=women" className="transition hover:text-primary">ЖЕНЩИНЫ</Link></nav></div></header>;
}

function Hero() {
  return <section className="relative min-h-[800px] overflow-hidden bg-background px-8 pt-16"><p className="text-[13px] font-medium text-black/60">Главная × RF Models</p><div className="grid gap-8 pt-8 lg:grid-cols-[1fr_530px]"><div><h1 className="max-w-5xl text-primary" style={{ fontFamily: "Italiana, serif", fontSize: "clamp(5rem, 13vw, 13.5rem)", lineHeight: .78, letterSpacing: "-.11em" }}>RF MODELS</h1><p className="mt-10 max-w-[430px] text-[24px] font-medium leading-[1.16] tracking-[-.03em]">модельное агентство с точным кастингом: женщины, мужчины и новые лица для съемок, показов и кампаний</p><div className="mt-14 flex flex-wrap gap-4"><Link to="/?gender=women" className="border border-primary px-8 py-5 text-2xl font-medium text-primary transition hover:bg-primary hover:text-primary-foreground">ЖЕНЩИНЫ</Link><Link to="/?gender=men" className="border border-primary px-8 py-5 text-2xl font-medium text-primary transition hover:bg-primary hover:text-primary-foreground">МУЖЧИНЫ</Link></div></div><div className="grid grid-cols-2 gap-5 self-start">{[hero, woman1, man1].map((img, i) => <ImageWithFallback key={img} src={img} alt="Портрет модели RF Models" className={`${i === 0 ? "col-span-2 h-[520px]" : "h-[250px]"} w-full object-cover`} />)}</div></div></section>;
}

function ModelCatalog() {
  const [params] = useSearchParams();
  const gender = params.get("gender");
  const visible = gender === "men" || gender === "women" ? models.filter((model) => model.gender === gender) : models;
  const title = gender === "men" ? "МУЖЧИНЫ" : gender === "women" ? "ЖЕНЩИНЫ" : "МОДЕЛИ";
  return <section id="models" className="bg-background px-8 py-20"><div className="grid gap-8 lg:grid-cols-[390px_1fr]"><aside><p className="text-xs font-semibold tracking-[.05em] text-muted-foreground">БЫСТРЫЙ ПОИСК</p><h2 className="mt-8 text-primary" style={{ fontFamily: "Italiana, serif", fontSize: "clamp(4.5rem,8vw,7rem)", lineHeight: .9, letterSpacing: "-.11em" }}>{title}</h2><p className="mt-10 text-[22px] font-medium leading-[1.18] tracking-[-.03em]">на главной показаны модели согласно дизайну; кнопки мужчин и женщин фильтруют подборку</p><div className="mt-10 flex flex-col gap-3 text-2xl font-medium"><Link to="/" className={!gender ? "text-primary underline" : "underline"}>ВСЕ</Link><Link to="/?gender=women" className={gender === "women" ? "text-primary underline" : "underline"}>ЖЕНЩИНЫ</Link><Link to="/?gender=men" className={gender === "men" ? "text-primary underline" : "underline"}>МУЖЧИНЫ</Link></div></aside><div className="grid gap-x-7 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{visible.map((model, i) => <Link key={model.id} to={`/models/${model.id}`} className="group block"><div className="overflow-hidden bg-muted"><ImageWithFallback src={model.image} alt={model.name} className={`${i % 3 === 1 ? "h-[460px]" : "h-[540px]"} w-full object-cover transition duration-500 group-hover:scale-105 group-hover:grayscale`} /></div><div className="mt-4 flex items-start justify-between border-b border-foreground/60 pb-3"><div><p className="text-[13px] font-semibold tracking-[.04em] text-muted-foreground">{model.category}</p><p className="mt-2 text-[32px] font-medium leading-none tracking-[-.06em]">{model.name}</p></div><span className="text-4xl text-primary">×</span></div></Link>)}</div></div></section>;
}

function AboutPage() { return <section className="grid min-h-[760px] gap-10 bg-background px-8 py-20 lg:grid-cols-[420px_1fr]"><div><p className="text-xs font-semibold tracking-[.05em] text-muted-foreground">ИСТОРИЯ RF MODELS</p><h2 className="mt-10 text-primary" style={{ fontFamily: "Italiana, serif", fontSize: "clamp(5rem,10vw,7.6rem)", lineHeight: .9, letterSpacing: "-.11em" }}>О НАС</h2><p className="mt-16 text-2xl font-medium leading-[1.15] tracking-[-.03em]">мы находим лица с характером и строим долгие модельные карьеры</p></div><div className="grid items-start gap-8 md:grid-cols-3"><ImageWithFallback src={woman4} alt="Модель в студии" className="mt-4 h-[262px] w-full object-cover"/><ImageWithFallback src={woman2} alt="Портрет модели" className="mt-16 h-[285px] w-full object-cover"/><ImageWithFallback src={man2} alt="Fashion портрет" className="h-[385px] w-full object-cover"/><div className="bg-primary p-8 text-primary-foreground md:col-span-2 md:col-start-2"><p className="text-sm font-semibold tracking-[.05em]">МОСКОВСКОЕ МОДЕЛЬНОЕ АГЕНТСТВО</p><p className="mt-3 max-w-lg text-xl leading-[1.1]">кастинг, развитие, портфолио, букинг и прямая коммуникация с брендами</p></div></div></section>; }
function ClientsPage() { return <section className="grid min-h-[760px] gap-8 bg-background px-8 py-20 lg:grid-cols-[390px_1fr]"><aside><p className="text-xs font-semibold tracking-[.05em] text-muted-foreground">НАШИ КЛИЕНТЫ</p><h2 className="mt-10 text-primary" style={{ fontFamily: "Italiana, serif", fontSize: "clamp(5rem,9vw,6.5rem)", letterSpacing: "-.12em" }}>КЛИЕНТЫ</h2><div className="mt-14 bg-primary p-8 text-primary-foreground"><p className="text-3xl font-medium tracking-[-.06em]">ВЫБРАННЫЕ<br/>ПРОЕКТЫ</p><p className="mt-16 text-lg">лукбук / кампания / подиум / примерка / шоурум</p></div></aside><div className="grid content-start gap-y-12 pt-8 sm:grid-cols-2 lg:grid-cols-3">{clients.map((client,i)=><a key={client} className="group flex gap-3 text-[32px] font-medium leading-none tracking-[-.06em] underline decoration-1 underline-offset-4"><span className="text-[13px] font-semibold tracking-normal text-muted-foreground">{String(i+1).padStart(2,"0")} /</span><span className="group-hover:text-primary">{client}</span></a>)}</div></section>; }
function BriefPage() { const [types,setTypes]=useState(["Женщины"]); return <section className="grid min-h-[860px] gap-10 bg-primary px-8 py-20 text-primary-foreground lg:grid-cols-[1fr_560px]"><div><h2 style={{fontFamily:"Italiana, serif",fontSize:"clamp(4.5rem,7vw,6rem)",lineHeight:.9,letterSpacing:"-.09em"}}>МЫ ВЫШЛЕМ ВАМ<br/>ПОДБОРКУ МОДЕЛЕЙ</h2><p className="mt-12 max-w-[410px] text-[22px] font-medium leading-[1.22]">заполните бриф — букер подготовит подходящие лица для вашей кампании</p><div className="mt-16 flex gap-8"><ImageWithFallback src={woman1} alt="Модель" className="h-72 w-56 object-cover"/><ImageWithFallback src={man1} alt="Модель" className="mt-[-30px] h-72 w-56 object-cover grayscale"/></div></div><form className="bg-card p-9 text-card-foreground"><h3 className="text-[25px] font-semibold tracking-[-.04em] text-primary">БРИФ ПРОЕКТА</h3><div className="mt-8 grid gap-x-9 gap-y-10 sm:grid-cols-2">{["01 / ИМЯ|Ваше имя","02 / ТЕЛЕФОН|+7 000 000-00-00","03 / БРЕНД ИЛИ АГЕНТСТВО|Название компании","04 / ДАТА СЪЕМКИ|MM.DD.YYYY","05 / БЮДЖЕТ|$ 10000"].map((field,i)=>{const [label,placeholder]=field.split("|");return <label key={label} className={`${i===2?"sm:col-span-2":""} block`}><span className="text-[13px] font-semibold tracking-[.04em] text-muted-foreground">{label}</span><input className="mt-4 w-full border-b border-foreground/70 bg-transparent pb-2 text-[22px] font-medium outline-none" placeholder={placeholder}/></label>})}</div><p className="mt-16 text-[13px] font-semibold tracking-[.04em] text-muted-foreground">06 / ТИП МОДЕЛИ</p><div className="mt-5 flex flex-wrap gap-7">{["Женщины","Мужчины","Новые лица"].map(type=><button key={type} type="button" onClick={()=>setTypes(types.includes(type)?types.filter(x=>x!==type):[...types,type])} className="flex items-center gap-3 text-xl"><span className={`size-6 border border-foreground ${types.includes(type)?"bg-primary":""}`}/>{type}</button>)}</div><button className="mt-10 flex h-[76px] w-full items-center justify-between border border-primary px-6 text-right text-[22px] font-semibold leading-none tracking-[-.02em] text-primary"><Plus/>ОТПРАВИТЬ<br/>ЗАЯВКУ</button></form></section>; }
function ContactsPage() { return <section className="grid min-h-[900px] gap-8 bg-[#eee8e8] px-8 py-20 lg:grid-cols-[430px_1fr_320px]"><div><h2 className="font-semibold uppercase leading-[1.05] tracking-[.66em] text-black" style={{fontSize:"clamp(3rem,5vw,4rem)"}}>Наши<br/>социальные<br/>сети</h2><p className="mt-24 text-primary text-6xl font-semibold">124.9 К</p><p className="mt-4 text-2xl font-semibold">ПОДПИСЧИКОВ</p></div><div className="grid grid-cols-2 gap-8"><ImageWithFallback src={detailMain} alt="Портрет модели" className="h-[539px] w-full object-cover"/><ImageWithFallback src={man1} alt="Портрет модели" className="mt-40 h-[539px] w-full object-cover"/></div><div className="self-end pb-10">{["FACEBOOK","INSTAGRAM","VK","TELEGRAM"].map(social=><a key={social} className="flex items-center gap-5 border-b border-primary py-6 text-4xl text-accent"><Plus light/>{social}</a>)}</div></section>; }

function HomePage() { return <><Hero /><ModelCatalog /><AboutPage /><ClientsPage /><BriefPage /><ContactsPage /></>; }
function CatalogOnlyPage() { return <ModelCatalog />; }
function ModelProfilePage() { const { id } = useParams(); const model = models.find((item) => item.id === id) ?? models[0]; return <section className="min-h-[1000px] bg-background px-8 py-8"><p className="pt-4 text-[13px] font-medium text-black/60">Главная × {model.gender === "men" ? "Мужчины" : "Женщины"} × {model.name}</p><div className="mt-10 grid gap-8 lg:grid-cols-[435px_1fr]"><ImageWithFallback src={model.id === "elvira-vaitovich" ? detailMain : model.image} alt={model.name} className="h-[585px] w-full object-cover"/><div><div className="grid grid-cols-2 gap-6 md:grid-cols-4">{model.shots.map((shot)=><ImageWithFallback key={shot} src={shot} alt={`Снимок ${model.name}`} className="h-[268px] w-full object-cover"/>)}<div className="bg-primary p-6 text-primary-foreground"><p className="text-sm font-semibold tracking-[.05em]">ДОСТУПНА</p><p className="mt-10 text-4xl font-medium leading-none tracking-[-.06em]">ДЛЯ<br/>БУКИНГА</p></div></div><p className="mt-14 text-[13px] font-semibold tracking-[.04em] text-muted-foreground">{model.category}</p><h1 className="mt-4 text-primary" style={{ fontFamily:"Italiana, serif", fontSize:"clamp(4.8rem,8vw,8.4rem)", lineHeight:.82, letterSpacing:"-.1em"}}>{model.name.split(" ").map((part)=><span key={part}>{part}<br/></span>)}</h1><div className="mt-8 grid max-w-[660px] grid-cols-2 gap-6 md:grid-cols-3">{model.stats.map(([key,value])=><div key={key} className="border-b border-foreground/60 pb-2"><p className="text-xs font-semibold uppercase tracking-[.05em] text-muted-foreground">{key}</p><b className="text-3xl tracking-[-.05em]">{value}</b></div>)}</div><div className="mt-10 flex flex-wrap gap-5"><Link to="/brief" className="inline-flex h-[76px] items-center gap-8 border border-foreground px-6 text-[22px] font-semibold tracking-[-.02em]"><Plus /> ЗАБРОНИРОВАТЬ</Link><Link to={`/?gender=${model.gender}`} className="text-xl font-medium tracking-[.1em] underline">НАЗАД К {model.gender === "men" ? "МУЖЧИНАМ" : "ЖЕНЩИНАМ"}</Link></div></div></div><h2 className="mt-12 text-primary" style={{ fontFamily:"Italiana, serif", fontSize:"clamp(5rem,10vw,7.25rem)", lineHeight:1, letterSpacing:"-.12em"}}>ПРОФИЛЬ</h2></section>; }
function Layout({ children }: { children: ReactNode }) { return <div className="min-h-screen bg-background text-foreground" style={{ backgroundImage: `linear-gradient(rgba(237,232,227,.92), rgba(237,232,227,.92)), url(${noise})` }}><Header /><main>{children}</main></div>; }
function NotFoundPage() { return <section className="min-h-[70vh] bg-background px-8 py-20"><p className="text-[13px] font-medium text-black/60">404 × Страница не найдена</p><h1 className="mt-10 text-primary" style={{ fontFamily: "Italiana, serif", fontSize: "clamp(5rem,12vw,10rem)", lineHeight: .85, letterSpacing: "-.11em" }}>НЕТ ТАКОЙ СТРАНИЦЫ</h1><Link to="/" className="mt-12 inline-flex h-[76px] items-center gap-10 border border-foreground px-6 text-[22px] font-semibold tracking-[-.02em]"><Plus /> НА ГЛАВНУЮ</Link></section>; }

const router = createBrowserRouter([
  { path: "/", Component: () => <Layout><HomePage /></Layout> },
  { path: "/about", Component: () => <Layout><AboutPage /></Layout> },
  { path: "/clients", Component: () => <Layout><ClientsPage /></Layout> },
  { path: "/women", Component: () => <Layout><CatalogOnlyPage /></Layout> },
  { path: "/brief", Component: () => <Layout><BriefPage /></Layout> },
  { path: "/contacts", Component: () => <Layout><ContactsPage /></Layout> },
  { path: "/models/:id", Component: () => <Layout><ModelProfilePage /></Layout> },
  { path: "*", Component: () => <Layout><NotFoundPage /></Layout> },
]);

export default function App() { return <RouterProvider router={router} />; }
